# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatLive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatLive
  
  pod 'Alamofire', '~> 4.0.1'
  pod 'Kingfisher', '~> 3.1.1'
	

end
